name: ideaship
description: "A Flutter project for ideaship."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:

  file_picker: ^8.1.3
  flutter_local_notifications: ^17.2.3 
  timezone: ^0.9.4  
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.0.5
  local_auth: ^2.3.0
  shared_preferences: ^2.3.0
  flutter_otp_text_field: ^1.1.3
  localstore: ^1.1.0
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  image_picker: ^1.2.0
  flutter_native_splash: ^2.4.6
  cached_network_image: ^3.3.1
  share_plus: ^7.2.1
  firebase_core: ^3.6.0  # Latest as of 2025
  firebase_messaging: ^15.1.3  # Latest as of 2025

  
  path_provider: ^2.0.14
  provider: ^6.0.5
  permission_handler: ^11.3.2
  url_launcher: ^6.3.2
  shimmer: ^3.0.0
  http_parser: ^4.1.2
  app_links: ^6.4.1
  photo_view: ^0.15.0
  lottie: ^3.1.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/black_logo.png

flutter_native_splash:
  color: "#FFFFFF"            
  image: assets/black_logo.png  
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android: true
  ios: true
  web: false
  android_12:
    color: "#FFFFFF"
    image: assets/black_logo.png
flutter_icons:
  android: true
  ios: true
  image_path: "assets/black_logo.png"   # path to your main logo
